name: genialisis_atleta_movil
description: "Captura de rendimiento deportivo - GENIALISIS"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # GPS: posición, velocidad
  geolocator: ^13.0.1
  # Acelerómetro y giroscopio
  sensors_plus: ^6.0.1
  # Grabar con el celular bloqueado (servicio en segundo plano)
  flutter_background_service: ^5.0.10
  # Pedir permisos (ubicación, notificaciones)
  permission_handler: ^11.3.1
  # Ubicación de carpetas para guardar archivos
  path_provider: ^2.1.4
  # Exportar / compartir el JSON
  share_plus: ^10.0.2
  # Crear el canal de notificación (requerido por el servicio en primer plano)
  flutter_local_notifications: ^18.0.1
  # Base de datos local SQLite (instituciones, atletas, sesiones)
  sqflite: ^2.3.3
  # Utilidad para construir rutas de archivos
  path: ^1.9.0
  # Elegir archivos del celular (para importar)
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png